// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.3
// source: proto/handshake.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandShake_HandShakeExchange_FullMethodName = "/bizzgrpc.HandShake/HandShakeExchange"
)

// HandShakeClient is the client API for HandShake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandShakeClient interface {
	HandShakeExchange(ctx context.Context, in *SendHandShake, opts ...grpc.CallOption) (*RecievedHandShake, error)
}

type handShakeClient struct {
	cc grpc.ClientConnInterface
}

func NewHandShakeClient(cc grpc.ClientConnInterface) HandShakeClient {
	return &handShakeClient{cc}
}

func (c *handShakeClient) HandShakeExchange(ctx context.Context, in *SendHandShake, opts ...grpc.CallOption) (*RecievedHandShake, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecievedHandShake)
	err := c.cc.Invoke(ctx, HandShake_HandShakeExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandShakeServer is the server API for HandShake service.
// All implementations must embed UnimplementedHandShakeServer
// for forward compatibility.
type HandShakeServer interface {
	HandShakeExchange(context.Context, *SendHandShake) (*RecievedHandShake, error)
	mustEmbedUnimplementedHandShakeServer()
}

// UnimplementedHandShakeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandShakeServer struct{}

func (UnimplementedHandShakeServer) HandShakeExchange(context.Context, *SendHandShake) (*RecievedHandShake, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandShakeExchange not implemented")
}
func (UnimplementedHandShakeServer) mustEmbedUnimplementedHandShakeServer() {}
func (UnimplementedHandShakeServer) testEmbeddedByValue()                   {}

// UnsafeHandShakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandShakeServer will
// result in compilation errors.
type UnsafeHandShakeServer interface {
	mustEmbedUnimplementedHandShakeServer()
}

func RegisterHandShakeServer(s grpc.ServiceRegistrar, srv HandShakeServer) {
	// If the following call pancis, it indicates UnimplementedHandShakeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandShake_ServiceDesc, srv)
}

func _HandShake_HandShakeExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendHandShake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandShakeServer).HandShakeExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandShake_HandShakeExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandShakeServer).HandShakeExchange(ctx, req.(*SendHandShake))
	}
	return interceptor(ctx, in, info, handler)
}

// HandShake_ServiceDesc is the grpc.ServiceDesc for HandShake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandShake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bizzgrpc.HandShake",
	HandlerType: (*HandShakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandShakeExchange",
			Handler:    _HandShake_HandShakeExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/handshake.proto",
}
