// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.3
// source: proto/handshake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendHandShake struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Instancemodule string                 `protobuf:"bytes,1,opt,name=instancemodule,proto3" json:"instancemodule,omitempty"`
	Instanceid     string                 `protobuf:"bytes,2,opt,name=instanceid,proto3" json:"instanceid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendHandShake) Reset() {
	*x = SendHandShake{}
	mi := &file_proto_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHandShake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHandShake) ProtoMessage() {}

func (x *SendHandShake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHandShake.ProtoReflect.Descriptor instead.
func (*SendHandShake) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *SendHandShake) GetInstancemodule() string {
	if x != nil {
		return x.Instancemodule
	}
	return ""
}

func (x *SendHandShake) GetInstanceid() string {
	if x != nil {
		return x.Instanceid
	}
	return ""
}

type RecievedHandShake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instanceid    string                 `protobuf:"bytes,1,opt,name=instanceid,proto3" json:"instanceid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecievedHandShake) Reset() {
	*x = RecievedHandShake{}
	mi := &file_proto_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecievedHandShake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecievedHandShake) ProtoMessage() {}

func (x *RecievedHandShake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecievedHandShake.ProtoReflect.Descriptor instead.
func (*RecievedHandShake) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *RecievedHandShake) GetInstanceid() string {
	if x != nil {
		return x.Instanceid
	}
	return ""
}

func (x *RecievedHandShake) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_handshake_proto protoreflect.FileDescriptor

const file_proto_handshake_proto_rawDesc = "" +
	"\n" +
	"\x15proto/handshake.proto\x12\bbizzgrpc\"W\n" +
	"\rSendHandShake\x12&\n" +
	"\x0einstancemodule\x18\x01 \x01(\tR\x0einstancemodule\x12\x1e\n" +
	"\n" +
	"instanceid\x18\x02 \x01(\tR\n" +
	"instanceid\"M\n" +
	"\x11RecievedHandShake\x12\x1e\n" +
	"\n" +
	"instanceid\x18\x01 \x01(\tR\n" +
	"instanceid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2V\n" +
	"\tHandShake\x12I\n" +
	"\x11HandShakeExchange\x12\x17.bizzgrpc.SendHandShake\x1a\x1b.bizzgrpc.RecievedHandShakeB\tZ\a./protob\x06proto3"

var (
	file_proto_handshake_proto_rawDescOnce sync.Once
	file_proto_handshake_proto_rawDescData []byte
)

func file_proto_handshake_proto_rawDescGZIP() []byte {
	file_proto_handshake_proto_rawDescOnce.Do(func() {
		file_proto_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_handshake_proto_rawDesc), len(file_proto_handshake_proto_rawDesc)))
	})
	return file_proto_handshake_proto_rawDescData
}

var file_proto_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_handshake_proto_goTypes = []any{
	(*SendHandShake)(nil),     // 0: bizzgrpc.SendHandShake
	(*RecievedHandShake)(nil), // 1: bizzgrpc.RecievedHandShake
}
var file_proto_handshake_proto_depIdxs = []int32{
	0, // 0: bizzgrpc.HandShake.HandShakeExchange:input_type -> bizzgrpc.SendHandShake
	1, // 1: bizzgrpc.HandShake.HandShakeExchange:output_type -> bizzgrpc.RecievedHandShake
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_handshake_proto_init() }
func file_proto_handshake_proto_init() {
	if File_proto_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_handshake_proto_rawDesc), len(file_proto_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_handshake_proto_goTypes,
		DependencyIndexes: file_proto_handshake_proto_depIdxs,
		MessageInfos:      file_proto_handshake_proto_msgTypes,
	}.Build()
	File_proto_handshake_proto = out.File
	file_proto_handshake_proto_goTypes = nil
	file_proto_handshake_proto_depIdxs = nil
}
