// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.3
// source: proto/heartbeat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	SignalId      string                 `protobuf:"bytes,2,opt,name=signalId,proto3" json:"signalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeartBeat) Reset() {
	*x = RequestHeartBeat{}
	mi := &file_proto_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeartBeat) ProtoMessage() {}

func (x *RequestHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeartBeat.ProtoReflect.Descriptor instead.
func (*RequestHeartBeat) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeartBeat) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RequestHeartBeat) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

type ReplyHeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	SignalId      string                 `protobuf:"bytes,2,opt,name=signalId,proto3" json:"signalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyHeartBeat) Reset() {
	*x = ReplyHeartBeat{}
	mi := &file_proto_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyHeartBeat) ProtoMessage() {}

func (x *ReplyHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyHeartBeat.ProtoReflect.Descriptor instead.
func (*ReplyHeartBeat) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyHeartBeat) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ReplyHeartBeat) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

var File_proto_heartbeat_proto protoreflect.FileDescriptor

const file_proto_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/heartbeat.proto\x12\bbizzgrpc\"N\n" +
	"\x10RequestHeartBeat\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bsignalId\x18\x02 \x01(\tR\bsignalId\"L\n" +
	"\x0eReplyHeartBeat\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bsignalId\x18\x02 \x01(\tR\bsignalId2V\n" +
	"\tHeartBeat\x12I\n" +
	"\x11HeartBeatExchange\x12\x1a.bizzgrpc.RequestHeartBeat\x1a\x18.bizzgrpc.ReplyHeartBeatB\tZ\a./protob\x06proto3"

var (
	file_proto_heartbeat_proto_rawDescOnce sync.Once
	file_proto_heartbeat_proto_rawDescData []byte
)

func file_proto_heartbeat_proto_rawDescGZIP() []byte {
	file_proto_heartbeat_proto_rawDescOnce.Do(func() {
		file_proto_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heartbeat_proto_rawDesc), len(file_proto_heartbeat_proto_rawDesc)))
	})
	return file_proto_heartbeat_proto_rawDescData
}

var file_proto_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_heartbeat_proto_goTypes = []any{
	(*RequestHeartBeat)(nil), // 0: bizzgrpc.RequestHeartBeat
	(*ReplyHeartBeat)(nil),   // 1: bizzgrpc.ReplyHeartBeat
}
var file_proto_heartbeat_proto_depIdxs = []int32{
	0, // 0: bizzgrpc.HeartBeat.HeartBeatExchange:input_type -> bizzgrpc.RequestHeartBeat
	1, // 1: bizzgrpc.HeartBeat.HeartBeatExchange:output_type -> bizzgrpc.ReplyHeartBeat
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_heartbeat_proto_init() }
func file_proto_heartbeat_proto_init() {
	if File_proto_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heartbeat_proto_rawDesc), len(file_proto_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_heartbeat_proto_goTypes,
		DependencyIndexes: file_proto_heartbeat_proto_depIdxs,
		MessageInfos:      file_proto_heartbeat_proto_msgTypes,
	}.Build()
	File_proto_heartbeat_proto = out.File
	file_proto_heartbeat_proto_goTypes = nil
	file_proto_heartbeat_proto_depIdxs = nil
}
